version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      exclude:
        - "@cmsgov/qpp-scoring-engines"
        - "qpp-measures-data"
        - "qpp-shared-logger-node"
