#
# This workflow will build codebase, run linting and test cases on every PR
# and push into develop and master branches.
#
name: Build - PR

on:
  push:
    branches: [ master ]

  pull_request:
    types: [ opened, synchronize, reopned ]
    branches: [ master ]

jobs:

  build:
    name: Build, Lint and Unit Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 12.15.0

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Create coverage folder
        run: mkdir -p coverage

      - name: Execute Unit Tests
        run: npm run test

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/cobertura-coverage.xml
